server:
  port: ${PORT:8080}

base:
  url: https://jsonplaceholder-gateway.herokuapp.com

spring:
  cloud:
    gateway:
      routes:
        - id: jsonplaceholder
          uri: https://jsonplaceholder.typicode.com/
          predicates:
            - Path=/api/jsonplaceholder/**